# Generated by Django 5.2 on 2025-08-20 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the disease', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the disease', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the plant (e.g., Eggplant, Tomato)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the plant', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the scan was performed.')),
                ('disease', models.ForeignKey(blank=True, help_text='The disease detected (if any). Can be null if no disease is found.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.disease')),
                ('plant', models.ForeignKey(blank=True, help_text='The type of plant scanned (e.g., Eggplant, Tomato)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.plant')),
                ('user', models.ForeignKey(help_text='The user who performed the scan', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Record',
                'verbose_name_plural': 'Scan Records',
                'ordering': ['-scan_date'],
            },
        ),
    ]
