# Generated by Django 5.2 on 2025-08-20 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='plants',
            field=models.ManyToManyField(blank=True, help_text='Select plants this disease can affect', related_name='diseases', to='detection.plant'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='disease',
            field=models.ForeignKey(blank=True, help_text='The disease detected (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.disease'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='plant',
            field=models.ForeignKey(blank=True, help_text='The type of plant scanned', null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.plant'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time of the scan'),
        ),
    ]
