# Generated by Django 5.2 on 2025-08-21 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_scan_confidence_scan_detected_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-scan_date'], 'verbose_name': 'Scan Record', 'verbose_name_plural': 'Scan Records'},
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the plant', null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the disease', null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(help_text='Name of the disease', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='plants',
            field=models.ManyToManyField(blank=True, help_text='Select plants this disease can affect', related_name='diseases', to='detection.plant'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention',
            field=models.TextField(blank=True, help_text='Prevention strategies for the disease', null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Symptoms of the disease', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text='Name of the plant (e.g., Eggplant, Tomato)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='disease',
            field=models.ForeignKey(blank=True, help_text='The disease detected (if any). Can be null if no disease is found.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.disease'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='plant',
            field=models.ForeignKey(blank=True, help_text='The type of plant scanned (e.g., Eggplant, Tomato)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.plant'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the scan was performed.'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(help_text='The user who performed the scan', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
    ]
