# Generated by Django 5.1.4 on 2025-11-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_alter_scan_options_plant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description_auto_tl',
            field=models.TextField(blank=True, help_text='Auto-translated Filipino description', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='description_manual_tl',
            field=models.TextField(blank=True, help_text='Manual Filipino description correction', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_auto_tl',
            field=models.TextField(blank=True, help_text='Auto-translated Filipino name', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_manual_tl',
            field=models.TextField(blank=True, help_text='Manual Filipino name correction', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_auto_tl',
            field=models.TextField(blank=True, help_text='Auto-translated Filipino prevention', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_manual_tl',
            field=models.TextField(blank=True, help_text='Manual Filipino prevention correction', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_auto_tl',
            field=models.TextField(blank=True, help_text='Auto-translated Filipino symptoms', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_manual_tl',
            field=models.TextField(blank=True, help_text='Manual Filipino symptoms correction', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='description_auto_tl',
            field=models.TextField(blank=True, help_text='Auto-translated Filipino description', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='description_manual_tl',
            field=models.TextField(blank=True, help_text='Manual Filipino description correction', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='name_auto_tl',
            field=models.TextField(blank=True, help_text='Auto-translated Filipino name', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='name_manual_tl',
            field=models.TextField(blank=True, help_text='Manual Filipino name correction', null=True),
        ),
    ]
