# Generated by Django 5.1.4 on 2025-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_disease_description_auto_tl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image that represents this disease', null=True, upload_to='disease_images/'),
        ),
    ]
