# detection/admin.py
from django.contrib import admin
from django.utils.html import format_html
from .models import Plant, Disease, Scan

class PlantAdmin(admin.ModelAdmin):
    list_display = ['name', 'name_manual_tl', 'name_auto_tl', 'plant_translation_status']
    list_filter = []
    search_fields = ['name', 'name_manual_tl', 'name_auto_tl']
    readonly_fields = ['name_auto_tl', 'description_auto_tl']
    
    fieldsets = (
        ('English Content (Original)', {
            'fields': ('name', 'description')
        }),
        ('Auto-Translated Filipino (System Generated)', {
            'fields': ('name_auto_tl', 'description_auto_tl'),
            'classes': ('collapse',),
            'description': 'These fields are automatically generated by the system. They are read-only.'
        }),
        ('Manual Filipino Correction (Override Auto-Translation)', {
            'fields': ('name_manual_tl', 'description_manual_tl'),
            'description': 'Use these fields to provide better translations. They will override auto-translations.'
        }),
    )
    
    def plant_translation_status(self, obj):
        """Show translation status in admin list with colors"""
        if obj.name_manual_tl:
            return format_html('<span style="color: green; font-weight: bold;">✅ Manual</span>')
        elif obj.name_auto_tl:
            return format_html('<span style="color: orange; font-weight: bold;">🤖 Auto</span>')
        else:
            return format_html('<span style="color: red; font-weight: bold;">❌ Not Translated</span>')
    plant_translation_status.short_description = 'Translation Status'
    
    actions = ['auto_translate_selected_plants']
    
    def auto_translate_selected_plants(self, request, queryset):
        """Admin action to auto-translate selected plants"""
        success_count = 0
        for plant in queryset:
            try:
                plant.auto_translate_all()
                success_count += 1
            except Exception as e:
                self.message_user(request, f"Failed to translate {plant.name}: {e}", level='error')
        
        self.message_user(request, f"✅ Auto-translated {success_count} plants successfully.")
    auto_translate_selected_plants.short_description = "Auto-translate selected plants"

class DiseaseAdmin(admin.ModelAdmin):
    list_display = ['name', 'name_manual_tl', 'name_auto_tl', 'disease_translation_status', 'get_plants_list', 'disease_image_preview']
    list_filter = ['plants']
    search_fields = ['name', 'name_manual_tl', 'name_auto_tl']
    readonly_fields = ['name_auto_tl', 'description_auto_tl', 'symptoms_auto_tl', 'prevention_auto_tl', 'disease_image_preview']
    filter_horizontal = ['plants']  # Better widget for many-to-many field
    
    fieldsets = (
        ('Basic Information', {
            'fields': ('name', 'description', 'symptoms', 'prevention', 'image', 'plants')
        }),
        ('Auto-Translated Filipino (System Generated)', {
            'fields': ('name_auto_tl', 'description_auto_tl', 'symptoms_auto_tl', 'prevention_auto_tl'),
            'classes': ('collapse',),
            'description': 'These fields are automatically generated by the system. They are read-only.'
        }),
        ('Manual Filipino Correction (Override Auto-Translation)', {
            'fields': ('name_manual_tl', 'description_manual_tl', 'symptoms_manual_tl', 'prevention_manual_tl'),
            'description': 'Use these fields to provide better translations. They will override auto-translations.'
        }),
    )
    
    def disease_translation_status(self, obj):
        """Show translation status in admin list with colors"""
        if obj.name_manual_tl:
            return format_html('<span style="color: green; font-weight: bold;">✅ Manual</span>')
        elif obj.name_auto_tl:
            return format_html('<span style="color: orange; font-weight: bold;">🤖 Auto</span>')
        else:
            return format_html('<span style="color: red; font-weight: bold;">❌ Not Translated</span>')
    disease_translation_status.short_description = 'Translation Status'
    
    def get_plants_list(self, obj):
        """Display plants as a comma-separated list"""
        return ", ".join([plant.name for plant in obj.plants.all()])
    get_plants_list.short_description = 'Affected Plants'
    
    def disease_image_preview(self, obj):
        """Display image preview in admin list and form"""
        if obj.image:
            return format_html(
                '<img src="{}" style="max-height: 50px; max-width: 50px; border-radius: 5px;" />',
                obj.image.url
            )
        return format_html('<span style="color: gray;">No image</span>')
    disease_image_preview.short_description = 'Image Preview'
    
    actions = ['auto_translate_selected_diseases']
    
    def auto_translate_selected_diseases(self, request, queryset):
        """Admin action to auto-translate selected diseases"""
        success_count = 0
        for disease in queryset:
            try:
                disease.auto_translate_all()
                success_count += 1
            except Exception as e:
                self.message_user(request, f"Failed to translate {disease.name}: {e}", level='error')
        
        self.message_user(request, f"✅ Auto-translated {success_count} diseases successfully.")
    auto_translate_selected_diseases.short_description = "Auto-translate selected diseases"

class ScanAdmin(admin.ModelAdmin):
    list_display = ['user', 'get_plant_name', 'get_disease_name', 'confidence', 'scan_date']
    list_filter = ['plant', 'scan_date', 'user']
    search_fields = ['user__username', 'plant__name', 'disease__name', 'detected_result']
    readonly_fields = ['scan_date', 'user', 'plant', 'disease', 'scanned_image', 'detected_result', 'confidence']
    
    fieldsets = (
        ('Scan Information', {
            'fields': ('user', 'scan_date', 'confidence')
        }),
        ('Detection Results', {
            'fields': ('plant', 'disease', 'detected_result')
        }),
        ('Uploaded Image', {
            'fields': ('scanned_image',),
            'classes': ('collapse',),
        }),
    )
    
    def get_plant_name(self, obj):
        """Display plant name with translation status"""
        if obj.plant:
            if obj.plant.name_manual_tl:
                return format_html('{} <span style="color: green;">(✓ Translated)</span>', obj.plant.name)
            elif obj.plant.name_auto_tl:
                return format_html('{} <span style="color: orange;">(Auto)</span>', obj.plant.name)
            else:
                return format_html('{} <span style="color: red;">(Not Translated)</span>', obj.plant.name)
        return "No Plant"
    get_plant_name.short_description = 'Plant'
    
    def get_disease_name(self, obj):
        """Display disease name with translation status"""
        if obj.disease:
            if obj.disease.name_manual_tl:
                return format_html('{} <span style="color: green;">(✓ Translated)</span>', obj.disease.name)
            elif obj.disease.name_auto_tl:
                return format_html('{} <span style="color: orange;">(Auto)</span>', obj.disease.name)
            else:
                return format_html('{} <span style="color: red;">(Not Translated)</span>', obj.disease.name)
        return "No Disease"
    get_disease_name.short_description = 'Disease'
    
    def has_add_permission(self, request):
        """Prevent manually adding scans - they should be created by the system"""
        return False
    
    def has_change_permission(self, request, obj=None):
        """Prevent editing scans - they are system records"""
        return False

# Custom Admin Site Header
admin.site.site_header = "E.T.C CAM Administration"
admin.site.site_title = "E.T.C CAM Admin Portal"
admin.site.index_title = "Welcome to E.T.C CAM Administration"

# Register models with custom admin classes
admin.site.register(Plant, PlantAdmin)
admin.site.register(Disease, DiseaseAdmin)
admin.site.register(Scan, ScanAdmin)